"""initial schema

Revision ID: 50e2c2c1cdda
Revises: 
Create Date: 2026-04-27 15:07:56.522063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50e2c2c1cdda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_display_id'), 'patient', ['display_id'], unique=True)
    op.create_index(op.f('ix_patient_full_name'), 'patient', ['full_name'], unique=False)
    op.create_index(op.f('ix_patient_national_id'), 'patient', ['national_id'], unique=True)
    op.create_table('systemsetting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemsetting_id'), 'systemsetting', ['id'], unique=True)
    op.create_index(op.f('ix_systemsetting_key'), 'systemsetting', ['key'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DOCTOR', 'RECEPTIONIST', name='userrole'), nullable=False),
    sa.Column('speciality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_display_id'), 'user', ['display_id'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('appointment_end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='appointmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_display_id'), 'appointment', ['display_id'], unique=True)
    op.create_table('visitnote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitnote')
    op.drop_index(op.f('ix_appointment_display_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_display_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_systemsetting_key'), table_name='systemsetting')
    op.drop_index(op.f('ix_systemsetting_id'), table_name='systemsetting')
    op.drop_table('systemsetting')
    op.drop_index(op.f('ix_patient_national_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_full_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_display_id'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
